# Generated by Django 5.0.7 on 2024-08-01 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('instrument', models.CharField(max_length=50, verbose_name='Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='RecordLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Label Name')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Album Title')),
                ('artist', models.CharField(max_length=200, verbose_name='Artist')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('album_members', models.ManyToManyField(blank=True, to='main_app.musician', verbose_name='Album Members')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recordlabel', verbose_name='Record Label')),
            ],
        ),
    ]
